INSERT INTO "role" (name) VALUES ('ROLE_USER');
INSERT INTO "role" (name) VALUES ('ROLE_ADMIN');
INSERT INTO "role" (name) VALUES ('ROLE_COTTAGE_OWNER');
INSERT INTO "role" (name) VALUES ('ROLE_BOAT_OWNER');
INSERT INTO "role" (name) VALUES ('ROLE_FISHING_INSTRUCTOR');